#!/usr/bin/env python3
"""
Example: How to use DML in agent workflows
This demonstrates practical integration patterns for DML.
"""

import sys
from typing import Any, Dict, Optional

sys.path.insert(0, '/home/nvidia/.npm-global_lib/node_modules/openclaw/node_modules/daystrom-dml')

from skills.daystrom_dml import DMLAgent


def example_basic_usage():
    """Example 1: Basic DML usage."""
    print("Example 1: Basic DML Usage\n")

    with DMLAgent() as dml:
        # Remember user preference
        dml.ingest(
            text="User prefers markdown over HTML for documentation",
            kind="preference",
            meta={"source": "example"}
        )

        # Remember task completion
        dml.ingest(
            text="Task 'fix DML skill' completed successfully",
            kind="action",
            meta={"task_id": 123, "status": "completed"}
        )

        # Get context for decision-making
        user_context = dml.get_context("user preferences")
        print(f"User context: {user_context}\n")

    print("✅ Basic usage completed")


def example_decision_support():
    """Example 2: Using DML for decision support."""
    print("\nExample 2: Decision Support\n")

    with DMLAgent() as dml:
        # Build context from multiple memories
        context = dml.get_context("decisions made")
        print(f"Context: {context[:200]}...\n")

        # Ingest new decision
        dml.ingest(
            text="User prefers dark mode by default and markdown documentation",
            kind="preference",
            meta={"decision_date": "2026-02-27", "type": "preference"}
        )

        print("✅ Decision support completed")


def example_preference_tracking():
    """Example 3: Tracking user preferences."""
    print("\nExample 3: Preference Tracking\n")

    with DMLAgent() as dml:
        preferences = [
            ("Markdown", "HTML"),
            ("Dark mode", "Light mode"),
            ("Python", "Node.js"),
            ("Conservative", "Experimental"),
        ]

        for name, value in preferences:
            dml.ingest(
                text=f"User prefers {name} over {value}",
                kind="preference",
                meta={"preference": name, "value": value}
            )

        # Get all preferences
        all_prefs = dml.get_context("user preferences")
        print(f"User preferences: {all_prefs}\n")

    print("✅ Preference tracking completed")


def example_memory_architecture():
    """Example 4: Memory architecture pattern."""
    print("\nExample 4: Memory Architecture\n")

    with DMLAgent() as dml:
        # Memory kinds
        kinds = {
            "preference": "User preferences",
            "action": "Completed actions",
            "observation": "Observed facts",
            "insight": "Learned insights",
            "planning": "Future plans",
            "execution": "Execution steps",
            "result": "Results achieved",
        }

        for kind_name, kind_desc in kinds.items():
            dml.ingest(
                text=f"Remember: {kind_desc}",
                kind=kind_name,
                meta={"type": kind_name}
            )

        # Get architecture context
        arch_context = dml.get_context("memory architecture")
        print(f"Memory architecture: {arch_context}\n")

    print("✅ Memory architecture completed")


def example_token_efficiency():
    """Example 5: Token efficiency demonstration."""
    print("\nExample 5: Token Efficiency\n")

    with DMLAgent() as dml:
        # Ingest detailed information
        detailed_info = """
        The AI system uses transformer architecture with attention mechanisms.
        It processes sequential data efficiently using self-attention layers.
        The model learns contextual relationships between tokens in the input sequence.
        Embedding vectors capture semantic meaning of each token.
        The output is generated by predicting the next token based on previous tokens.
        """

        dml.ingest(detailed_info, kind="action")

        # Retrieve summarized version
        retrieved = dml.get_context("transformer architecture")
        tokens_saved = len(detailed_info) - len(retrieved)

        print(f"Original: {len(detailed_info)} chars ({len(detailed_info)/4:.0f} tokens)")
        print(f"Retrieved: {len(retrieved)} chars ({len(retrieved)/4:.0f} tokens)")
        print(f"Tokens saved: {tokens_saved/4:.0f} ({tokens_saved/4/len(detailed_info)/4*100:.1f}%)\n")

    print("✅ Token efficiency demonstrated")


def example_long_term_memory():
    """Example 6: Long-term memory persistence."""
    print("\nExample 6: Long-Term Memory\n")

    with DMLAgent() as dml:
        # Simulate multi-day activity
        days = 7

        for day in range(1, days + 1):
            for activity in [
                f"Day {day}: Completed daily tasks",
                f"Day {day}: Improved system performance",
                f"Day {day}: Fixed minor bugs",
            ]:
                dml.ingest(activity, kind="action", meta={"day": day})

        # Check memory count
        count = dml.memory_count()
        print(f"Memories after {days} days: {count}\n")

        # Retrieve context from all days
        context = dml.get_context("activities over time")
        print(f"Retrieved context: {len(context)} chars ({len(context)/4:.0f} tokens)\n")

    print("✅ Long-term memory completed")


if __name__ == "__main__":
    print("=" * 60)
    print("DML Integration Examples")
    print("=" * 60)

    example_basic_usage()
    example_decision_support()
    example_preference_tracking()
    example_memory_architecture()
    example_token_efficiency()
    example_long_term_memory()

    print("\n" + "=" * 60)
    print("✅ All examples completed successfully!")
    print("=" * 60)