-- Generated by journal.py at b8626b73b2caeab2a7c25353d11aa526adf777a2; commit fixture, not a release tag.
BEGIN TRANSACTION;
CREATE TABLE decisions (revision INTEGER PRIMARY KEY, payload TEXT, checksum TEXT NOT NULL);
INSERT INTO "decisions" VALUES(1,'{"changed":[{"bucket":"items","digest":"3ab35e6eef26ab303e4ab2c8984c0c3279a1ed1a336d6f18c7a721bad406da05","id":"1"}],"deleted":[],"operation":"legacy-first","record_count":1,"revision":1,"schema_version":1,"state_digest":"4c2eb96a45b7a512bb9f62b2c26445e6ab51b8c2be421449ec41f072c6e5d48f"}','8b0a675a609ef80ce4ad3f48937d7cbb50ca22bc3f878853a0f9dcc3a3ba7495');
INSERT INTO "decisions" VALUES(2,'{"changed":[{"bucket":"items","digest":"163037cc735deff9ff471ffeb88684a4629b474f5835a8e18f16f04494861ff7","id":"1"}],"deleted":[],"operation":"legacy-second","record_count":1,"revision":2,"schema_version":1,"state_digest":"c23b80716e955eaa43044bc9f81beda45d2cb1bcff68900b07001829e5365e4d"}','de24798dd8081582dab879e58040627df00783030fd4528ae31033a22e1fffce');
CREATE TABLE identity (id INTEGER PRIMARY KEY CHECK(id=1), store_id TEXT NOT NULL);
INSERT INTO "identity" VALUES(1,'2f64b0d280134d258001a32713339f36');
CREATE TABLE records (bucket TEXT, key TEXT, position INTEGER, payload TEXT, checksum TEXT NOT NULL, PRIMARY KEY(bucket,key));
INSERT INTO "records" VALUES('items','1',0,'{"id":1,"text":"updated schema-1 evidence"}','163037cc735deff9ff471ffeb88684a4629b474f5835a8e18f16f04494861ff7');
CREATE TABLE snapshot (id INTEGER PRIMARY KEY CHECK(id=1), revision INTEGER, payload TEXT, checksum TEXT NOT NULL);
INSERT INTO "snapshot" VALUES(1,1,'{"items":[{"id":1,"text":"original schema-1 evidence"}],"lineage":[],"next_id":2}','4c2eb96a45b7a512bb9f62b2c26445e6ab51b8c2be421449ec41f072c6e5d48f');
CREATE TABLE state (id INTEGER PRIMARY KEY CHECK(id=1), revision INTEGER, metadata TEXT, checksum TEXT NOT NULL);
INSERT INTO "state" VALUES(1,2,'{"next_id":2}','3000388d170da9cc15ce303fcd475d29002df8e667eac898e4b0bfb07c90e76c');
COMMIT;
PRAGMA user_version=1;
