"""Daystrom Context Manager contract primitives."""
from daystrom_dml.context.admission import ACTIVE_ADMISSION_MODE, ADMISSION_MODES, OBSERVE_ONLY_MODE, admit_context_segments
from daystrom_dml.context.budget import ContextBudget
from daystrom_dml.context.capabilities import RUNTIME_CAPABILITIES_V1, RuntimeCapabilities
from daystrom_dml.context.catalog import PAGE_CATALOG_V1, PageCatalogQuery, PageCatalogResult, SemanticPageCatalog
from daystrom_dml.context.checkpoints import (
    EXECUTION_CHECKPOINT_IDENTITY_V1,
    EXECUTION_CHECKPOINT_IDENTITY_V2,
    EXECUTION_CHECKPOINT_RECORD_V1,
    CheckpointPurgeResult,
    CheckpointRestoreResult,
    CheckpointSelectionError,
    ExecutionCheckpointController,
    ExecutionCheckpointIdentity,
    ExecutionCheckpointRecord,
    FileExecutionCheckpointRegistry,
)
from daystrom_dml.context.execution import (
    RuntimeCacheOperation,
    RuntimeCacheOperationResult,
    RuntimeCheckpointDeleteResult,
    RuntimeCompletionTrace,
    RuntimeExecutionCapabilities,
    RuntimeExecutionError,
)
from daystrom_dml.context.kv_fabric import (
    KV_OBJECT_DESCRIPTOR_V1,
    KV_TIER_ENDPOINT_CAPABILITY_V1,
    KV_TIER_SEMANTICS_V1,
    KV_TRANSFER_PLAN_V1,
    KV_TRANSFER_TICKET_V1,
    KVDurability,
    KVLocality,
    KVObjectDescriptor,
    KVRoutePlanner,
    KVTierEndpointCapability,
    KVTierKind,
    KVTierSemantics,
    KVTransferDirection,
    KVTransferHop,
    KVTransferMechanism,
    KVTransferPlan,
    KVTransferTicket,
    KVTransferTicketIssuer,
    KVTransportCapability,
    runtime_compatibility_digest,
    tier_semantics_for_kind,
)
from daystrom_dml.context.manifest import CONTEXT_MANIFEST_V1, CONTEXT_PACKET_V1, ContextManifest, ContextPacket
from daystrom_dml.context.native_transition import (
    NATIVE_CONTEXT_CHECKPOINT_BINDING_V1,
    NATIVE_CONTEXT_TRANSITION_V1,
    NativeContextCheckpointBinding,
    NativeContextPage,
    NativeContextRuntimeStep,
    NativeContextTransitionCompiler,
    NativeContextTransitionPlan,
)
from daystrom_dml.context.recovery import (
    AutonomousFaultRetryRunner,
    CheckpointRecoveryPlan,
    FaultRetryPolicy,
    FaultRetryResult,
    RecoveryStatus,
)
from daystrom_dml.context.schema import ContextAuthority, ContextPriority, ContextSegment, context_segment_digest
from daystrom_dml.context.working_set import WORKING_SET_TRANSITION_V1, WorkingSetManager

__all__ = [
    "ACTIVE_ADMISSION_MODE",
    "ADMISSION_MODES",
    "AutonomousFaultRetryRunner",
    "CheckpointRecoveryPlan",
    "CONTEXT_MANIFEST_V1",
    "CONTEXT_PACKET_V1",
    "ContextAuthority",
    "ContextBudget",
    "CheckpointPurgeResult",
    "CheckpointRestoreResult",
    "CheckpointSelectionError",
    "ContextManifest",
    "ContextPacket",
    "ContextPriority",
    "ContextSegment",
    "EXECUTION_CHECKPOINT_IDENTITY_V1",
    "EXECUTION_CHECKPOINT_IDENTITY_V2",
    "EXECUTION_CHECKPOINT_RECORD_V1",
    "ExecutionCheckpointController",
    "ExecutionCheckpointIdentity",
    "ExecutionCheckpointRecord",
    "FaultRetryPolicy",
    "FaultRetryResult",
    "FileExecutionCheckpointRegistry",
    "KVDurability",
    "KVLocality",
    "KVObjectDescriptor",
    "KVRoutePlanner",
    "KVTierEndpointCapability",
    "KVTierKind",
    "KVTierSemantics",
    "KVTransferDirection",
    "KVTransferHop",
    "KVTransferMechanism",
    "KVTransferPlan",
    "KVTransferTicket",
    "KVTransferTicketIssuer",
    "KVTransportCapability",
    "runtime_compatibility_digest",
    "KV_OBJECT_DESCRIPTOR_V1",
    "KV_TIER_ENDPOINT_CAPABILITY_V1",
    "KV_TIER_SEMANTICS_V1",
    "KV_TRANSFER_PLAN_V1",
    "KV_TRANSFER_TICKET_V1",
    "NATIVE_CONTEXT_TRANSITION_V1",
    "NATIVE_CONTEXT_CHECKPOINT_BINDING_V1",
    "NativeContextCheckpointBinding",
    "NativeContextPage",
    "NativeContextRuntimeStep",
    "NativeContextTransitionCompiler",
    "NativeContextTransitionPlan",
    "OBSERVE_ONLY_MODE",
    "PAGE_CATALOG_V1",
    "PageCatalogQuery",
    "PageCatalogResult",
    "RUNTIME_CAPABILITIES_V1",
    "RuntimeCacheOperation",
    "RuntimeCacheOperationResult",
    "RuntimeCheckpointDeleteResult",
    "RuntimeCompletionTrace",
    "RecoveryStatus",
    "RuntimeCapabilities",
    "RuntimeExecutionCapabilities",
    "RuntimeExecutionError",
    "SemanticPageCatalog",
    "WORKING_SET_TRANSITION_V1",
    "WorkingSetManager",
    "admit_context_segments",
    "context_segment_digest",
    "tier_semantics_for_kind",
]
